name: Pages

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Checkout private submodules(themes or something else).

      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
      - name: Cache node modules
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      # Deploy hexo blog website.
#      - name: Deploy
#        id: deploy
#        uses: sma11black/hexo-action@v1.0.3
#        with:
#          deploy_key: ${{ secrets.DEPLOY_KEY }}
#          user_name: healthy-tree # (or delete this input setting to use bot account)
#          user_email: lishu5566@gmail.com  # (or delete this input setting to use bot account)
#          commit_msg: ${{ github.event.head_commit.message }}  # (or delete this input setting to use hexo default settings)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # deploying branch
      # Use the output from the `deploy` step(use for test action)
      - name: Get the output
        run: |
          echo "${{ steps.deploy.outputs.notify }}"
#  pages:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Use Node.js 18.x
#        uses: actions/setup-node@v1
#        with:
#          node-version: '18.x'
#      - name: Cache NPM dependencies
#        uses: actions/cache@v4
#        with:
#          path: node_modules
#          key: ${{ runner.OS }}-npm-cache
#          restore-keys: |
#            ${{ runner.OS }}-npm-cache
#      - name: Install Dependencies
#        run: npm install
#      - name: Build
#        run: npm run build
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public
#          publish_branch: gh-pages  # deploying branch
